name: Feature Request (Maintainers Only)
description: For maintainers to track new features. Community members, please use Discussions.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **This template is intended for maintainers only.**

        If you are a community member with a feature idea, please share it in our [Discussions (Ideas)](https://github.com/b4m-oss/bwenv/discussions/categories/ideas) instead.
        Issues created by non-maintainers using this template may be converted to discussions.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed? What problem does it solve?
      placeholder: Explain the motivation behind this feature...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature be implemented? Any technical details or ideas?
      placeholder: Describe your proposed solution...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or references here.
    validations:
      required: false


